name: Build Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔨 Build frontend
        run: npm run build

      - name: 🚀 Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "."              # raíz del repo
          output_location: "dist"        # carpeta de salida de Vite
          azure_static_web_apps_api_token: ${{ secrets.AZURE_FRONTEND_TOKEN }}
